name: CI
on: [push]
jobs:



  cache-submodule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: env/setup.sh
    - uses: ./.github/actions/submodule



  build-lnx-bld:
    needs: [cache-submodule]
    runs-on: ubuntu-latest

    steps:
    - run: sudo rm -rf /opt

    - uses: actions/checkout@v4

    - run: docker build --build-arg GIT_REPOSITORY=https://github.com/${{ github.repository }}.git --build-arg GIT_COMMIT=${{ github.sha }} --build-arg GIT_SETUP=env/setup-git.sh -t orchidd:latest srv-docker
    - run: docker save -o orchidd.tar orchidd:latest

    - uses: actions/upload-artifact@v4
      with:
        name: orchidd-dkr
        path: orchidd.tar


  build-lnx-mac:
    needs: [cache-submodule]
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - run: env/setup.sh
    - uses: ./.github/actions/submodule

    - uses: ./.github/actions/nerdctl
    - run: printenv
    - run: env/setup-ndk.sh
    - run: printenv

    - run: gmake -j3 -C srv-daemon target=lnx

    - uses: actions/upload-artifact@v4
      with:
        name: orchidd-lnx-amd64
        path: srv-daemon/out-lnx/x86_64/orchidd



  build-lnx-all:
    needs: [build-lnx-mac, build-lnx-bld]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: orchidd-dkr
    - run: tar -xvf orchidd.tar
    - run: tar -xvf "$(jq -r '.[0].Layers | .[]' manifest.json | tail -n1)"

    - uses: actions/download-artifact@v4
      with:
        name: orchidd-lnx-amd64

    - run: chmod +x orchidd
    - run: diff -u <(./usr/sbin/orchidd --version) <(./orchidd --version)
    - run: diff -u <(xxd usr/sbin/orchidd) <(xxd orchidd)



